# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
    - parallel:
      - step:
          name: Agent
          caches:
            - dotnetcore
          script: # Modify the commands below to build your repository.
            - export PROJECT_NAME=TheProjectGame/Agent
            - export TEST_NAME=TheProjectGame/AgentTests
            - dotnet restore $PROJECT_NAME/Agent.csproj
            - dotnet restore $TEST_NAME/AgentTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: CommunicationServer
          caches:
            - dotnetcore
          script: # Modify the commands below to build your repository.
            - export PROJECT_NAME=TheProjectGame/CommunicationServer
            - export TEST_NAME=TheProjectGame/CommunicationServerTests
            - dotnet restore $PROJECT_NAME/CommunicationServer.csproj
            - dotnet restore $TEST_NAME/CommunicationServerTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: GameMaster
          caches:
            - dotnetcore
          script: # Modify the commands below to build your repository.
            - export PROJECT_NAME=TheProjectGame/GameMaster
            - export TEST_NAME=TheProjectGame/GameMasterTests
            - dotnet restore $PROJECT_NAME/GameMaster.csproj
            - dotnet restore $TEST_NAME/GameMasterTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
