image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  branches: 
    master:
    - step:
        name: Messaging
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=TheProjectGame/Messaging
          - export TEST_NAME=TheProjectGame/MessagingTests
          - dotnet restore $PROJECT_NAME/Messaging.csproj
          - dotnet restore $TEST_NAME/MessagingTests.csproj
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
    - parallel:
      - step:
          name: Agent
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/Agent
            - export TEST_NAME=TheProjectGame/AgentTests
            - dotnet restore $PROJECT_NAME/Agent.csproj
            - dotnet restore $TEST_NAME/AgentTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: CommunicationServer
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/CommunicationServer
            - export TEST_NAME=TheProjectGame/CommunicationServerTests
            - dotnet restore $PROJECT_NAME/CommunicationServer.csproj
            - dotnet restore $TEST_NAME/CommunicationServerTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: GameMaster
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/GameMaster
            - export TEST_NAME=TheProjectGame/GameMasterTests
            - dotnet restore $PROJECT_NAME/GameMaster.csproj
            - dotnet restore $TEST_NAME/GameMasterTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
    development:
    - step:
        name: Messaging
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=TheProjectGame/Messaging
          - export TEST_NAME=TheProjectGame/MessagingTests
          - dotnet restore $PROJECT_NAME/Messaging.csproj
          - dotnet restore $TEST_NAME/MessagingTests.csproj
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
    - parallel:
      - step:
          name: Agent
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/Agent
            - export TEST_NAME=TheProjectGame/AgentTests
            - dotnet restore $PROJECT_NAME/Agent.csproj
            - dotnet restore $TEST_NAME/AgentTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: CommunicationServer
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/CommunicationServer
            - export TEST_NAME=TheProjectGame/CommunicationServerTests
            - dotnet restore $PROJECT_NAME/CommunicationServer.csproj
            - dotnet restore $TEST_NAME/CommunicationServerTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
      - step:
          name: GameMaster
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=TheProjectGame/GameMaster
            - export TEST_NAME=TheProjectGame/GameMasterTests
            - dotnet restore $PROJECT_NAME/GameMaster.csproj
            - dotnet restore $TEST_NAME/GameMasterTests.csproj
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME